name: Deploy on Main

on:
  push:
    branches:
      - main

env:
  AWS_ROLE_ARN: arn:aws:iam::445605964569:role/assume_role_github_actions
  AWS_DEFAULT_REGION: ap-northeast-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Apply
        run: terraform apply -auto-approve